### ISSUE TITLE
Bug in original paper

### ISSUE THREAD

**Issue by KMahoney** [ericnormand/hindley-milner#1]
I encountered a bug in the paper you based this on. You might want to make sure you haven't replicated it!

https://github.com/KMahoney/Algorithm-W-Step-By-Step/commit/418a30900a8406ee9c90b19358eae85cccaab8f9

**Comment by ericnormand** [comment]
Hi Kevin,

I noticed that, too, when I was implementing it. Are you sure it's a bug?
Looking closely at composeSubst, it looks commutative to me. Do you have a
test case that does not infer correctly?

Thanks
Eric

On Mon, Jan 13, 2014 at 4:31 PM, Kevin Mahoney notifications@github.comwrote:

> I encountered a bug in the paper you based this on. You might want to make
> sure you haven't replicated it!
> 
> KMahoney/Algorithm-W-Step-By-Step@418a309https://github.com/KMahoney/Algorithm-W-Step-By-Step/commit/418a30900a8406ee9c90b19358eae85cccaab8f9
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ericnormand/hindley-milner/issues/1
> .

## 

Eric Normand
Chief Instigator, LispCast

Learn Clojure: http://videos.lispcast.com http://videos.lispcast.com

**Comment by KMahoney** [comment]
I added a failing test case here: https://github.com/KMahoney/Algorithm-W-Step-By-Step/commit/2c5be9380eddf52365e91f00f478ee5e76ed9db1

As you can see I fixed this a couple of years ago so the details are hazy, but the merge is not commutative as if a key exists in both maps it will use the second operand's value. I'll need to remind myself what's going on here - it's been a while.

**Comment by ericnormand** [comment]
Cool, thanks! I'll add that test case.

Eric

On Tue, Jan 14, 2014 at 8:08 AM, Kevin Mahoney notifications@github.comwrote:

> I added a failing test case here: KMahoney/Algorithm-W-Step-By-Step@
> 2c5be93https://github.com/KMahoney/Algorithm-W-Step-By-Step/commit/2c5be9380eddf52365e91f00f478ee5e76ed9db1
> 
> As you can see I fixed this a couple of years ago so the details are hazy,
> but the merge is not commutative as if a key exists in both maps it will
> use the second operand's value. I'll need to remind myself what's going on
> here - it's been a while.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ericnormand/hindley-milner/issues/1#issuecomment-32266873
> .

## 

Eric Normand
Chief Instigator, LispCast

Learn Clojure: http://videos.lispcast.com http://videos.lispcast.com

**Comment by ericnormand** [comment]
Fixed. Thanks!
